version: "3.7"
services:
  app:
    build:
      args:
        user: gesiel
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: hpm
    container_name: hpm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app/:/var/www
    networks:
      - hpm

  db:
    image: postgres:12.0-alpine
    container_name: hpm-db
    restart: always
    environment:
      POSTGRES_USER: gesiel
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: hpmdatabase 
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    networks:
      - hpm
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: hpm-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www
      - ./.docker/nginx/hpm.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hpm

  redis:
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    image: redis
    privileged: true
    command: sh -c "./init.sh"
    container_name: hpm-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./.docker/redis:/bitnami/redis/data
    ports:
      - 6379-6379
    networks:
      - hpm

networks:
  hpm:
    driver: bridge